name: p1
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v'
        type: string
      dry_run:
        description: 'd'
        type: boolean
        default: false
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - run: echo p1
