name: p2
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
  workflow_call:
    inputs:
      version:
        type: string
        required: true
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - run: echo p2
