name: p3
on:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  j:
    if: startsWith(github.event.release.tag_name, 'v') && !github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - run: echo p3
